version: '3.9'
services:
  feelapp:
    image: feelapp/odoo:15.0
    container_name: feelapp-prod
    restart: always
    environment:
     - TZ=America/Bogota
    ports:
     - "8069:8069"
     - "8071:8071"
     - "8072:8072"
    networks:
      portainer_default:
        aliases:
         - feelapp
    volumes:
      - ./log:/opt/odoo/log
      - ./config/:/opt/odoo/config/
      - /opt/odoo/addons/:/opt/odoo/extra-addons
      - /opt/odoo/filestore/:/opt/odoo/data
      - /opt/odoo/location/:/opt/odoo/location
      - /opt/odoo/enterprise/:/opt/odoo/enterprise
      - /opt/odoo/backup/google/:/opt/odoo/backup/google-drive
networks:
    portainer_default:
            external: true
            name: portainer_default
