version: '3.9'
services:
  feelapp:
    image: feelapp/odoo:17.0                 # Ejemplo del nombre de la imagen
    container_name: feelapp-prod
    restart: unless-stopped
    environment:
     - TZ=America/Bogota
    ports:
     - "8069:8069"
     - "8072:8072"
    networks:
      portainer_default:
        aliases:
         - feelapp                           # Ejemplo nombre de la red
    volumes:
      - ./log:/opt/odoo/log                     # Directorio no presistente
      - ./config/odoo/:/opt/odoo/config/        # Directorio no persistente
      - /opt/odoo/odoo:/opt/odoo/odoo           
      - /opt/odoo/addons/:/opt/odoo/extra-addons
      - /opt/odoo/enterprise/:/opt/odoo/enterprise
      - /opt/odoo/location/:/opt/odoo/location
      - /opt/odoo/data/:/opt/odoo/data
      - /opt/odoo/backup/:/opt/odoo/backup
networks:
    portainer_default:
            external:
            name: portainer_default
