version: '3.9'
services:
  feelapp:
    image: feelapp/odoo:12.0
    container_name: feelapp-prod
#    ports:
#     - 8070:8070
    networks:
      portainer_default:
        aliases:
          - feelapp
    volumes:
      - ./log:/opt/odoo/log
      - ./config:/opt/odoo/config
      - /home/feelapp/addons/:/opt/odoo/extra-addons
      - /home/feelapp/backup/:/opt/odoo/data
      - /home/feelapp/location/:/opt/odoo/location
      - /home/feelapp/enterprise/:/opt/odoo/enterprise
      - /home/feelapp/themes/:/opt/odoo/themes
networks:
    portainer_default:
            external: true
            name: portainer_default
