version: '3.9'
services:
  feelapp:
    image: feelapp/odoo:15.0
    container_name: feelapp-prod
    restart: always
    environment:
     - TZ=America/Bogota
    ports:
     - "8069:8069"
     - "8071:8071"
     - "8072:8072"
    networks:
      portainer_default:
        aliases:
         - feelapp
    volumes:
      - ./log:/opt/odoo/log
      - ./config:/opt/odoo/config
      - /home/feelapp/addons/:/opt/odoo/extra-addons
      - /home/feelapp/filestore/:/opt/odoo/data
      - /home/feelapp/location/:/opt/odoo/location
      - /home/feelapp/enterprise/:/opt/odoo/enterprise
      - /home/feelapp/themes/:/opt/odoo/themes
      - /home/feelapp/google/:/opt/odoo/google/drive
networks:
    portainer_default:
            external: true
            name: portainer_default
